# Assignment 4

Before working on this assignment please read these instructions fully. In the submission area, you will notice that you can click the link to **Preview the Grading** for each step of the assignment. This is the criteria that will be used for peer grading. Please familiarize yourself with the criteria before beginning the assignment.

This assignment requires that you to find **at least** two datasets on the web which are related, and that you visualize these datasets to answer a question with the broad topic of **sports or athletics** (see below) for the region of **Ann Arbor, Michigan, United States**, or **United States** more broadly.

You can merge these datasets with data from different regions if you like! For instance, you might want to compare **Ann Arbor, Michigan, United States** to Ann Arbor, USA. In that case at least one source file must be about **Ann Arbor, Michigan, United States**.

You are welcome to choose datasets at your discretion, but keep in mind **they will be shared with your peers**, so choose appropriate datasets. Sensitive, confidential, illicit, and proprietary materials are not good choices for datasets for this assignment. You are welcome to upload datasets of your own as well, and link to them using a third party repository such as github, bitbucket, pastebin, etc. Please be aware of the Coursera terms of service with respect to intellectual property.

Also, you are welcome to preserve data in its original language, but for the purposes of grading you should provide english translations. You are welcome to provide multiple visuals in different languages if you would like!

As this assignment is for the whole course, you must incorporate principles discussed in the first week, such as having as high data-ink ratio (Tufte) and aligning with Cairoâ€™s principles of truth, beauty, function, and insight.

Here are the assignment instructions:

 * State the region and the domain category that your data sets are about (e.g., **Ann Arbor, Michigan, United States** and **sports or athletics**).
 * You must state a question about the domain category and region that you identified as being interesting.
 * You must provide at least two links to available datasets. These could be links to files such as CSV or Excel files, or links to websites which might have data in tabular form, such as Wikipedia pages.
 * You must upload an image which addresses the research question you stated. In addition to addressing the question, this visual should follow Cairo's principles of truthfulness, functionality, beauty, and insightfulness.
 * You must contribute a short (1-2 paragraph) written justification of how your visualization addresses your stated research question.

What do we mean by **sports or athletics**?  For this category we are interested in sporting events or athletics broadly, please feel free to creatively interpret the category when building your research question!

## Tips
* Wikipedia is an excellent source of data, and I strongly encourage you to explore it for new data sources.
* Many governments run open data initiatives at the city, region, and country levels, and these are wonderful resources for localized data sources.
* Several international agencies, such as the [United Nations](http://data.un.org/), the [World Bank](http://data.worldbank.org/), the [Global Open Data Index](http://index.okfn.org/place/) are other great places to look for data.
* This assignment requires you to convert and clean datafiles. Check out the discussion forums for tips on how to do this from various sources, and share your successes with your fellow students!

## Example
Looking for an example? Here's what our course assistant put together for the **Ann Arbor, MI, USA** area using **sports and athletics** as the topic. [Example Solution File](./readonly/Assignment4_example.pdf)

In [15]:
import pandas as pd

In [16]:
spartans_batting  = pd.read_csv('spartans_batting.csv')
spartans_pitching = pd.read_csv('spartans_pitching.csv')

blue_batting  = pd.read_csv('goblue_batting.csv')
blue_pitching = pd.read_csv('goblue_pitching.csv')

In [17]:
print(spartans_batting.head())
print(spartans_pitching.head())
print(blue_batting.head())
print(blue_pitching.head())

        Date  Loc          Opponent W/L Score  AB  R   H  RBI  2B  ...  CS  \
0  2/15/2019  at        New Orleans   W   8-4  32  8   6    4   1  ...   0
1  2/16/2019  at        New Orleans   L   1-4  36  1  11    1   1  ...   0
2  2/17/2019  at        New Orleans   L   4-6  32  4  10    4   2  ...   1
3  2/22/2019  at   Coastal Carolina   L  0-13  30  0   2    0   0  ...   0
4  2/22/2019  at   Coastal Carolina   L  5-12  35  5   9    5   1  ...   0

   HBP  SH  SF  GDP   K  PO   A  E    AVG
0    0   0   0    1  12  27   4  1  0.188
1    1   0   0    1   4  24  10  1  0.306
2    0   1   0    1   4  24   6  1  0.313
3    1   0   0    0  10  24   8  3  0.067
4    0   1   0    0  11  24   9  2  0.257

[5 rows x 25 columns]
        Date  Loc          Opponent W/L Score   IP   H   R  ER  BB  ...  HR  \
0  2/15/2019  at        New Orleans   W   8-4  9.0   7   4   4   9  ...   1
1  2/16/2019  at        New Orleans   L   1-4  8.0   8   4   4   3  ...   0
2  2/17/2019  at        New Orleans   L   4-6  8.0   9   6   6   4  ...   2
3  2/22/2019  at   Coastal Carolina   L  0-13  8.0  15  13  10   4  ...   3
4  2/22/2019  at   Coastal Carolina   L  5-12  8.0  18  12  12   7  ...   1

   WP  BK  HDP  IBB  SCORE  W  L SV    ERA
0   3   0    1    0    8-4  1  0  1   4.00
1   1   0    2    0    1-4  1  1  0   4.50
2   2   0    1    1    4-6  1  2  0   6.75
3   2   0    3    0   0-13  1  3  0  11.25
4   3   0    2    0   5-12  1  4  0  13.50

[5 rows x 23 columns]
        Date  Loc     Opponent W/L Score  AB   R   H  RBI  2B  ...  CS  HBP  \
0  2/15/2019  vs    Binghamton   W  10-0  31  10  11    8   3  ...   0    2
1  2/16/2019  vs    Binghamton   W   5-4  30   5   7    5   2  ...   1    0
2  2/17/2019  vs    Binghamton   W  12-2  34  12  12   12   1  ...   0    3
3  2/22/2019  at   The Citadel   W   2-0  32   2   8    2   1  ...   0    1
4  2/23/2019  at   The Citadel   W   9-1  40   9  12    9   3  ...   0    0

   SH  SF  GDP   K  PO   A  E    AVG
0   1   1    2   6  27  10  1  0.355
1   0   0    0   7  27  11  5  0.233
2   0   3    1   5  27  12  1  0.353
3   0   1    2   8  27   8  0  0.250
4   0   0    0  10  27  11  0  0.300

[5 rows x 25 columns]
        Date  Loc     Opponent W/L Score  IP  H  R  ER  BB  ...  HR  WP  BK  \
0  2/15/2019  vs    Binghamton   W  10-0   9  7  0   0   1  ...   0   1   0
1  2/16/2019  vs    Binghamton   W   5-4   9  4  4   1   1  ...   0   2   0
2  2/17/2019  vs    Binghamton   W  12-2   9  8  2   2   3  ...   0   0   0
3  2/22/2019  at   The Citadel   W   2-0   9  1  0   0   0  ...   0   0   0
4  2/23/2019  at   The Citadel   W   9-1   9  4  1   1   1  ...   1   0   0

   HDP  IBB  SCORE  W  L SV  ERA
0    1    0   10-0  1  0  1  0.0
1    0    0    5-4  2  0  1  1.0
2    0    0   12-2  3  0  0  2.0
3    0    0    2-0  4  0  0  0.0
4    1    0    9-1  5  0  0  1.0

[5 rows x 23 columns]

In [29]:
df = spartans_batting.copy()

print(spartans_batting.shape)
print(blue_batting.shape)
print(spartans_batting.columns)
print(blue_batting.columns)

print(blue_batting.columns.to_list() == spartans_batting.columns.to_list())

(54, 25)
(72, 25)
Index(['Date', 'Loc', 'Opponent', 'W/L', 'Score', 'AB', 'R', 'H', 'RBI', '2B',
       '3B', 'HR', 'BB', 'IBB', 'SB', 'CS', 'HBP', 'SH', 'SF', 'GDP', 'K',
       'PO', 'A', 'E', 'AVG'],
      dtype='object')
Index(['Date', 'Loc', 'Opponent', 'W/L', 'Score', 'AB', 'R', 'H', 'RBI', '2B',
       '3B', 'HR', 'BB', 'IBB', 'SB', 'CS', 'HBP', 'SH', 'SF', 'GDP', 'K',
       'PO', 'A', 'E', 'AVG'],
      dtype='object')

True

In [19]:
df.append(blue_batting)

,Date,Loc,Opponent,W/L,Score,AB,R,H,RBI,2B,...,CS,HBP,SH,SF,GDP,K,PO,A,E,AVG
0,2/15/2019,at,New Orleans,W,8-4,32,8,6,4,1,...,0,0,0,0,1,12,27,4,1,0.188
1,2/16/2019,at,New Orleans,L,1-4,36,1,11,1,1,...,0,1,0,0,1,4,24,10,1,0.306
2,2/17/2019,at,New Orleans,L,4-6,32,4,10,4,2,...,1,0,1,0,1,4,24,6,1,0.313
3,2/22/2019,at,Coastal Carolina,L,0-13,30,0,2,0,0,...,0,1,0,0,0,10,24,8,3,0.067
4,2/22/2019,at,Coastal Carolina,L,5-12,35,5,9,5,1,...,0,0,1,0,0,11,24,9,2,0.257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,6/17/2019,vs,Florida State,W,2-0,34,2,7,2,0,...,1,0,0,0,0,17,27,5,0,0.206
68,6/21/2019,vs,Texas Tech,W,15-3,38,15,14,14,3,...,0,3,0,0,0,11,27,14,0,0.368
69,6/24/2019,vs,Vanderbilt,W,7-4,39,7,14,7,3,...,0,0,1,0,0,13,27,11,1,0.359
70,6/25/2019,vs,Vanderbilt,L,1-4,32,1,4,1,0,...,0,0,1,0,0,13,27,9,2,0.125
71,6/26/2019,vs,Vanderbilt,L,2-8,33,2,6,2,2,...,0,0,0,0,0,14,24,6,0,0.182